name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set Build Date
        id: date
        run: echo "::set-output name=BUILD_DATE::$(date +'%Y-%m-%d')"

      - name: Build and Push Docker Image
        run: |
          # Build the Docker image with the build date tag
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/vscode-tunnel:${{ steps.date.outputs.BUILD_DATE }} .

          # Tag the built image as "latest"
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/vscode-tunnel:${{ steps.date.outputs.BUILD_DATE }} ${{ secrets.DOCKERHUB_USERNAME }}/vscode-tunnel:latest

          # Push the image with the build date tag
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vscode-tunnel:${{ steps.date.outputs.BUILD_DATE }}

          # Push the image with the "latest" tag
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vscode-tunnel:latest
